version: "3.9"

services:
  sealguard-admin:
    container_name: sealguard-admin
    image: yuanyuexiang/sealguard-admin:v1
    restart: always
    healthcheck:
      disable: true
    ports:
      - "3000:3000"
    networks:
      - matrix-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sealguard-admin.rule=Host(`sealguard.matrix-net.tech`)"
      - "traefik.http.routers.sealguard-admin.entrypoints=websecure"
      - "traefik.http.routers.sealguard-admin.service=sealguard-admin"
      - "traefik.http.routers.sealguard-admin.tls.certresolver=aliyunresolver"
      - "traefik.http.services.sealguard-admin.loadbalancer.server.port=3000"

  sealguard-api:
    container_name: sealguard-api
    image: yuanyuexiang/sealguard-api:v1
    restart: always
    ports:
      - "8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:123456@postgres:5432/sealguard
    volumes:
      - ./data/sealguard-api:/app/runtime
    networks:
      - matrix-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sealguard-api.rule=Host(`sealguard.matrix-net.tech`) && (PathPrefix(`/api`) || PathPrefix(`/health`))" # 替换为你的域名
      - "traefik.http.routers.sealguard-api.entrypoints=websecure"
      - "traefik.http.routers.sealguard-api.service=sealguard-api"
      - "traefik.http.routers.sealguard-api.tls=true"
      - "traefik.http.routers.sealguard-api.tls.certresolver=aliyunresolver"
      - "traefik.http.services.sealguard-api.loadbalancer.server.port=8000"

networks:
  matrix-network:
    external: true
